theme: jekyll-theme-dinky
title: ReadME
description: This will display progress, pair share journal, test prep
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  README.md
